"""
safety.py
=========
Emergency kill-switch and takeover-detection via low-level Win32 global hooks.

Design
------
- WH_MOUSE_LL  → detect mouse movement delta > threshold OR any physical button press
- WH_KEYBOARD_LL → detect ESC key (VK_ESCAPE = 0x1B)
- On trigger: atomically flip AgentState → INTERRUPTED; broadcast an Event so that
  any waiting caller can react in < 10 ms.
- Hooks run on a dedicated daemon thread that owns its own Win32 message pump
  so they work regardless of whether the main thread has a message loop.

Thread safety
-------------
AgentState is a plain IntEnum stored behind a threading.Lock + threading.Event.
All reads/writes go through StateManager which provides lock-free fast-path
reads via a volatile-alike atomic int using ctypes.c_int + a Python Lock for writes.
"""

from __future__ import annotations

import ctypes
import ctypes.wintypes
import threading
import logging
import atexit
from enum import IntEnum
from typing import Callable, Optional

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Win32 constants & structures
# ---------------------------------------------------------------------------

WH_KEYBOARD_LL: int = 13
WH_MOUSE_LL: int = 14

WM_KEYDOWN: int = 0x0100
WM_SYSKEYDOWN: int = 0x0104
WM_MOUSEMOVE: int = 0x0200
WM_LBUTTONDOWN: int = 0x0201
WM_RBUTTONDOWN: int = 0x0204
WM_MBUTTONDOWN: int = 0x0207

VK_ESCAPE: int = 0x1B

HC_ACTION: int = 0

PM_REMOVE: int = 0x0001

# MSLLHOOKSTRUCT.flags bit: set when the event was injected by SendInput /
# SetCursorPos rather than generated by physical hardware.
LLMHF_INJECTED: int = 0x00000001
LLMHF_LOWER_IL_INJECTED: int = 0x00000002  # injected from lower-IL process

# ---------------------------------------------------------------------------
# 64-bit-safe HOOKPROC callback type and Win32 function declarations
# ---------------------------------------------------------------------------
# On 64-bit Windows, WPARAM = UINT_PTR (8 bytes) and LPARAM = LONG_PTR (8 bytes).
# ctypes.wintypes.WPARAM / LPARAM are only 4 bytes on all platforms — using them
# in a WINFUNCTYPE on x64 causes silent truncation or OverflowErrors.
_IS_64: bool = ctypes.sizeof(ctypes.c_void_p) == 8
_WPARAM_T  = ctypes.c_uint64 if _IS_64 else ctypes.c_uint32
_LPARAM_T  = ctypes.c_int64  if _IS_64 else ctypes.c_int32
_LRESULT_T = ctypes.c_int64  if _IS_64 else ctypes.c_long
_HHOOK_T   = ctypes.c_void_p  # HHOOK is a pointer-sized handle

_HOOKPROC_TYPE = ctypes.WINFUNCTYPE(_LRESULT_T, ctypes.c_int, _WPARAM_T, _LPARAM_T)

# Declare CallNextHookEx argtypes so ctypes passes 64-bit lParam correctly.
# Without this, Python silently truncates the value to 32 bits on x64.
_user32_s = ctypes.windll.user32  # type: ignore[attr-defined]
_user32_s.CallNextHookEx.restype  = _LRESULT_T
_user32_s.CallNextHookEx.argtypes = [
    _HHOOK_T,       # hhk  (HHOOK, may be NULL)
    ctypes.c_int,   # nCode
    _WPARAM_T,      # wParam
    _LPARAM_T,      # lParam
]


class KBDLLHOOKSTRUCT(ctypes.Structure):
    """Low-level keyboard hook data (MSDN: KBDLLHOOKSTRUCT)."""

    _fields_ = [
        ("vkCode", ctypes.wintypes.DWORD),
        ("scanCode", ctypes.wintypes.DWORD),
        ("flags", ctypes.wintypes.DWORD),
        ("time", ctypes.wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]


class MSLLHOOKSTRUCT(ctypes.Structure):
    """Low-level mouse hook data (MSDN: MSLLHOOKSTRUCT)."""

    _fields_ = [
        ("pt", ctypes.wintypes.POINT),
        ("mouseData", ctypes.wintypes.DWORD),
        ("flags", ctypes.wintypes.DWORD),
        ("time", ctypes.wintypes.DWORD),
        ("dwExtraInfo", ctypes.POINTER(ctypes.c_ulong)),
    ]


# ---------------------------------------------------------------------------
# Agent state
# ---------------------------------------------------------------------------


class AgentState(IntEnum):
    """Lifecycle state of the agent execution engine."""

    IDLE = 0
    ACTIVE = 1
    INTERRUPTED = 2


# ---------------------------------------------------------------------------
# State manager – ultra-thin lock + event wrapper
# ---------------------------------------------------------------------------


class _StateManager:
    """Thread-safe container for AgentState with observer support."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._state: AgentState = AgentState.IDLE
        self._interrupt_event = threading.Event()
        self._callbacks: list[Callable[[AgentState], None]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    @property
    def state(self) -> AgentState:
        with self._lock:
            return self._state

    @state.setter
    def state(self, new_state: AgentState) -> None:
        with self._lock:
            if self._state == new_state:
                return
            self._state = new_state
            if new_state == AgentState.INTERRUPTED:
                self._interrupt_event.set()
            elif new_state == AgentState.ACTIVE:
                self._interrupt_event.clear()
            callbacks = list(self._callbacks)

        # Fire callbacks outside lock to avoid deadlocks
        for cb in callbacks:
            try:
                cb(new_state)
            except Exception:
                logger.exception("State callback raised an exception")

    def wait_for_interrupt(self, timeout: Optional[float] = None) -> bool:
        """Block until INTERRUPTED; return True if interrupted, False on timeout."""
        return self._interrupt_event.wait(timeout)

    def is_interrupted(self) -> bool:
        return self._interrupt_event.is_set()

    def register_callback(self, cb: Callable[[AgentState], None]) -> None:
        with self._lock:
            self._callbacks.append(cb)

    def unregister_callback(self, cb: Callable[[AgentState], None]) -> None:
        with self._lock:
            try:
                self._callbacks.remove(cb)
            except ValueError:
                pass


# ---------------------------------------------------------------------------
# Safety monitor
# ---------------------------------------------------------------------------


class SafetyMonitor:
    """
    Installs WH_MOUSE_LL and WH_KEYBOARD_LL hooks and provides an interrupt
    mechanism for the agent execution engine.

    Parameters
    ----------
    state_manager : _StateManager
        Shared state object (owned by the engine singleton).
    move_threshold : int
        Mouse displacement (Manhattan distance) that triggers a takeover abort.
    """

    def __init__(
        self,
        state_manager: _StateManager,
        move_threshold: int = 15,
    ) -> None:
        self._sm = state_manager
        self._move_threshold = move_threshold

        # Last known mouse position for delta computation
        self._last_pt: Optional[ctypes.wintypes.POINT] = None
        self._last_pt_lock = threading.Lock()

        # Hook handles (HHOOK)
        self._mouse_hook: Optional[int] = None
        self._kbd_hook: Optional[int] = None

        # The hook thread owns the message pump
        self._hook_thread: Optional[threading.Thread] = None
        self._hook_thread_id: int = 0
        self._hook_ready = threading.Event()
        self._stop_requested = threading.Event()

        # Keep strong references to HOOKPROC callbacks to prevent GC.
        # Using the module-level 64-bit-safe type defined above.
        self._mouse_cb = _HOOKPROC_TYPE(self._mouse_hook_proc)
        self._kbd_cb   = _HOOKPROC_TYPE(self._kbd_hook_proc)

        self._user32 = ctypes.windll.user32  # type: ignore[attr-defined]

        atexit.register(self.stop)

    # ------------------------------------------------------------------
    # Public lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Install hooks and begin monitoring on a dedicated daemon thread."""
        if self._hook_thread is not None and self._hook_thread.is_alive():
            return
        self._stop_requested.clear()
        self._hook_ready.clear()
        self._hook_thread = threading.Thread(
            target=self._hook_thread_main,
            name="SafetyMonitor-HookThread",
            daemon=True,
        )
        self._hook_thread.start()
        if not self._hook_ready.wait(timeout=3.0):
            raise RuntimeError("SafetyMonitor: hook thread failed to initialise within 3 s")
        logger.info("SafetyMonitor: hooks installed (move_threshold=%d px)", self._move_threshold)

    def stop(self) -> None:
        """Remove hooks and stop the monitoring thread."""
        self._stop_requested.set()
        if self._hook_thread_id:
            # Post WM_QUIT to the hook thread's message queue
            self._user32.PostThreadMessageW(self._hook_thread_id, 0x0012, 0, 0)  # WM_QUIT
        if self._hook_thread is not None:
            self._hook_thread.join(timeout=2.0)
        logger.info("SafetyMonitor: stopped")

    def reset(self) -> None:
        """Arm for the next agent task (clear interrupt, reset last position)."""
        with self._last_pt_lock:
            self._last_pt = None
        # Caller is expected to set state → ACTIVE afterwards

    # ------------------------------------------------------------------
    # Hook procedures (called on the hook thread)
    # ------------------------------------------------------------------

    def _mouse_hook_proc(
        self,
        nCode: int,
        wParam: int,
        lParam: int,
    ) -> int:
        try:
            if nCode == HC_ACTION and self._sm.state == AgentState.ACTIVE:
                data = ctypes.cast(lParam, ctypes.POINTER(MSLLHOOKSTRUCT)).contents

                # ── Synthetic-event guard ──────────────────────────────────
                # LLMHF_INJECTED is set whenever the event was produced by
                # SendInput or SetCursorPos (i.e. by *us*).  Counting those
                # as physical movement would create an immediate false-positive
                # kill-switch trigger on every agent click.
                is_injected = bool(data.flags & (LLMHF_INJECTED | LLMHF_LOWER_IL_INJECTED))

                if wParam == WM_MOUSEMOVE:
                    if not is_injected:
                        self._check_mouse_delta(data.pt)
                    else:
                        # Keep reference point in sync so the first real move
                        # after an injected one is measured from the right place.
                        with self._last_pt_lock:
                            self._last_pt = data.pt
                elif wParam in (WM_LBUTTONDOWN, WM_RBUTTONDOWN, WM_MBUTTONDOWN):
                    # Physical button press counts as takeover only if not injected
                    if not is_injected:
                        self._trigger_interrupt("physical mouse button press")
        except Exception:
            logger.exception("Exception in mouse hook proc")
        return self._user32.CallNextHookEx(self._mouse_hook, nCode, wParam, lParam)

    def _kbd_hook_proc(
        self,
        nCode: int,
        wParam: int,
        lParam: int,
    ) -> int:
        try:
            if nCode == HC_ACTION and self._sm.state == AgentState.ACTIVE:
                if wParam in (WM_KEYDOWN, WM_SYSKEYDOWN):
                    data = ctypes.cast(lParam, ctypes.POINTER(KBDLLHOOKSTRUCT)).contents
                    if data.vkCode == VK_ESCAPE:
                        self._trigger_interrupt("ESC key pressed")
        except Exception:
            logger.exception("Exception in keyboard hook proc")
        return self._user32.CallNextHookEx(self._kbd_hook, nCode, wParam, lParam)

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _check_mouse_delta(self, pt: ctypes.wintypes.POINT) -> None:
        with self._last_pt_lock:
            if self._last_pt is None:
                self._last_pt = pt
                return
            dx = abs(pt.x - self._last_pt.x)
            dy = abs(pt.y - self._last_pt.y)
            self._last_pt = pt

        if dx + dy > self._move_threshold:
            self._trigger_interrupt(f"mouse moved {dx+dy} px (threshold={self._move_threshold})")

    def _trigger_interrupt(self, reason: str) -> None:
        logger.warning("SafetyMonitor: INTERRUPT – %s", reason)
        self._sm.state = AgentState.INTERRUPTED

    def _hook_thread_main(self) -> None:
        """Dedicated thread: install hooks → run message pump → uninstall hooks."""
        # GetCurrentThreadId lives in kernel32, NOT user32.
        _kernel32 = ctypes.windll.kernel32  # type: ignore[attr-defined]
        self._hook_thread_id = _kernel32.GetCurrentThreadId()

        self._mouse_hook = self._user32.SetWindowsHookExW(
            WH_MOUSE_LL,
            self._mouse_cb,
            None,
            0,
        )
        if not self._mouse_hook:
            err = ctypes.get_last_error()
            logger.error("SetWindowsHookExW(WH_MOUSE_LL) failed, error=%d", err)

        self._kbd_hook = self._user32.SetWindowsHookExW(
            WH_KEYBOARD_LL,
            self._kbd_cb,
            None,
            0,
        )
        if not self._kbd_hook:
            err = ctypes.get_last_error()
            logger.error("SetWindowsHookExW(WH_KEYBOARD_LL) failed, error=%d", err)

        self._hook_ready.set()

        # Message pump – required for low-level hooks to receive events.
        # GetMessageW blocks until a message arrives (0% idle CPU), unlike the
        # previous PeekMessage + sleep(1 ms) busy-wait approach.
        # WM_QUIT (posted by stop()) causes GetMessageW to return 0 → loop exits.
        msg = ctypes.wintypes.MSG()
        while True:
            ret = self._user32.GetMessageW(ctypes.byref(msg), None, 0, 0)
            if ret == 0 or ret == -1:  # WM_QUIT or error
                break
            self._user32.TranslateMessage(ctypes.byref(msg))
            self._user32.DispatchMessageW(ctypes.byref(msg))

        # Cleanup – always unhook regardless of how we exited the loop
        if self._mouse_hook:
            self._user32.UnhookWindowsHookEx(self._mouse_hook)
            self._mouse_hook = None
        if self._kbd_hook:
            self._user32.UnhookWindowsHookEx(self._kbd_hook)
            self._kbd_hook = None
